name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build App
      run: 
        go build -v ./...

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Start Container
      run: |
        docker-compose -f "docker-compose.yml" up -d --build
       
    - name: Check Running Container
      run: 
        docker ps
    
    - name: Unit Testing
      run: |
        docker-compose exec -i app go test ./controllers -v -coverprofile=coverage.out
        docker-compose exec -i app go tool cover -html=coverage.out -o coverage.html